version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "02:00"
      open-pull-requests-limit: 10
      reviewers:
          - "stevenleep"
      assignees:
          - "stevenleep"
      commit-message:
          prefix: "deps"
          include: "scope"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "02:00"
      open-pull-requests-limit: 5
      reviewers:
          - "stevenleep"
      assignees:
          - "stevenleep"
      commit-message:
          prefix: "ci"
          include: "scope"
